# Generated by Django 4.0 on 2023-12-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
