# Generated by Django 4.0 on 2023-12-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('cantidad_materias', models.IntegerField()),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.instituto')),
            ],
        ),
    ]
