# Generated by Django 4.0 on 2023-12-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
